databases:
  - name: mHabbit
    databaseName: mHabbit
    user: mHabbit

services:
  - type: web
    name: mHabbit
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mHabbit
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false