databases:
  - name: masked
    databaseName: masked
    user: masked
    plan: free # optional (defaults to starter)

services:
  - type: web
    name: masked
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: masked
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false