databases:
  - name: maskedHabbit
    databaseName: maskedHabbit
    user: maskedHabbit

services:
  - type: web
    name: maskedHabbit
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maskedHabbit
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false